
[theme]
primaryColor = "#57150B"           # Rowan Brown: strong, traditional, and wise (just like Whoo RU!)
backgroundColor = "#FFF8E1"        # A warm, inviting light cream for a cozy feel
secondaryBackgroundColor = "#FFCC00"  # Rowan Gold: vibrant and full of school spirit
textColor = "#262730"             # Dark text for excellent readability
font = "sans serif"               # Clean and modern—perfect for our Profs!
